name: sign

on:
  push:
    tags:
    - '*'

jobs:
  sign-ext:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v4

      # Get nodejs env
      - uses: actions/setup-node@v4

      # Install and run sign
      - env:
          WEB_EXT_API_SECRET: ${{ secrets.FF_API_SECRET }}
          WEB_EXT_API_KEY: ${{ secrets.FF_API_KEY }}
        run: |
          sed -i "s/CI_COMMIT_TAG/${GITHUB_REF_NAME}/" manifest.json
          npm install --global web-ext
          web-ext sign --channel unlisted --ignore-files "info/*"
          mv ./web-ext-artifacts/*.xpi ./web-ext-artifacts/gitlab-pipeline-variables-${GITHUB_REF_NAME}.xpi

      # Add xpi to release
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/web-ext-artifacts/*.xpi
